apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-v1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-v1
  template:
    metadata:
      labels:
        app: web-v1
    spec:
      containers:
      - name: nginx
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
