apiVersion: v1
kind: Pod
metadata:
  name: test-empty-dir
spec:
  containers:
  - image: nginx
    name: nginx
    ports: 
    - containerPort: 80
    volumeMounts:
    - mountPath: /mnt/work/nginx/html
      name: emptydir-volume
  volumes:
  - name: emptydir-volume
    emptyDir: {}