apiVersion: v1
kind: Pod
metadata:
  name: test-host-volume
spec:
  containers:
  - image: nginx
    name: nginx
    ports: 
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: hostvolume-vol
  - image: debian
    name: debian
    volumeMounts:
    - mountPath: /mnt/trabajo
      name: hostvolume-vol
    command: ["/bin/sh", "-c", "echo Kubernetes y no morir en el intento >> /mnt/trabajo/index.html ; sleep 3600"]
  volumes:
  - name: hostvolume-vol
    hostPath:
      path: /home/docker/pod-volume
      type: Directory
  